### Numpy

> ->Numarical python

> -> Numpy is multi dimensional array....

> its a python labrary 

> it faster as compared to python 

> it is faster as compared to python list 

> here we go with bunch of mathamaticl funcation for array operatation 

> we can intigrate with other librese like pandas matplotlib scikit-learn

In [4]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


##### installing Numpy

In [5]:
! pip install numpy

In [6]:
import numpy as np
np.array([1, 2, 3,"hello"])

array(['1', '2', '3', 'hello'], dtype='<U21')

In [7]:
narray=np.array([1, 2, 3,"hello"])

In [8]:
type(narray)

numpy.ndarray

In [9]:
narray.shape

(4,)

In [10]:
n2=[[1,2],[3,4]]
arr=np.array(n2)


In [11]:
arr = np.zeros((3, 4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
n1=np.array([3,4,5])
n2=np.array([6,7,8])


In [13]:
n1.shape

(3,)

In [14]:
n1*n2

array([18, 28, 40])

In [15]:
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[0:4])

[1 2 3 4]


##### 1D array

arr[arr>3]

In [17]:
arr[arr>3]

array([4, 5, 6, 7, 8, 9])

#### reshaping of array

In [19]:
arr=np.arange(10)

In [20]:
len(arr)

10

In [42]:
arr=arr.reshape(2,5)


In [43]:
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

#### Matrix multiplication

In [ ]:
m1=np.once((3,2))
m2=np.arry((2,3))